server:
  port: 9000
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha

spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema-h2.sql
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:admin
    username: admin
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect